# docker-compose.yml for timescale
version: '3.1'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
