version: '3.1'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/home/postgres/pgdata/data
    restart: always
